set -g status-left "#[bold]  #S"
set -g status-right " #{cpu -i 3} |  #{mem} "
set -g status-justify centre
set -g window-status-format "#I:#W"
set -g window-status-current-format "#[fg=#88C0D0,bg=default] #I:#W"

set-option -g status-style bg=default
