set -g default-terminal "tmux-256color"
set -as terminal-features ',*:RGB'

set -g set-clipboard on
set -g mouse on

set -sg escape-time 10 # Fix helix delay when switching modes
set -g detach-on-destroy off # Stay in tmux when the last session is closed

# Refresh tmux using `r`
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Split horizontally
unbind %
bind \\ split-window -h -c "${pane_current_path}"

# Split vertically
unbind \"
bind - split-window -v -c "#{pane_current_path}"

# New window in the same path
bind c new-window -c "#{pane_current_path}"

# Start windows numbering from 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# style constants
soft_white=#DCD7BA
muted_gold=#E6C384

# set status bar styling
set -g status-position top
set -g status-left-length 100
set -g status-right-length 100
set -g status-style "fg=${soft_white},bg=default"
set -g status-left "#[fg=${soft_white},bold]#S #[fg=${soft_white},nobold] | "
set -g status-right " CPU: #{cpu} |  MEM: #{mem -t} | 󱛟 DISK: #{disk -t}"
set -g window-status-current-format "#[fg=${muted_gold},bold]  #I:#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${soft_white},bg=default"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
