vim.wo.number = true -- Line numbers
vim.o.relativenumber = true --Relative line numbers
vim.o.clipboard = "unnamedplus"
vim.o.linebreak = true
vim.o.autoindent = true
vim.o.smartindent = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.o.scrolloff = 4
vim.o.sidescrolloff = 8
vim.o.cursorline = false
vim.o.splitbelow = true
vim.o.splitright = true
vim.opt.termguicolors = true
vim.o.numberwidth = 4
vim.o.swapfile = false
vim.o.showtabline = 2
vim.o.backspace = "indent,eol,start"
vim.o.pumheight = 10
vim.o.conceallevel = 0
vim.o.signcolumn = "yes"
vim.o.fileencoding = "utf-8"
vim.o.cmdheight = 0
vim.o.breakindent = true
vim.o.updatetime = 250
vim.o.timeoutlen = 300
vim.o.backup = false
vim.o.writebackup = false
vim.o.undofile = true
vim.opt.runtimepath:remove "/usr/share/vim/vimfiles"
